//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zerohunger.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable1
    {
        public int Employeeid { get; set; }
        public string Employeename { get; set; }
        public int completedrequest { get; set; }
        public string location { get; set; }
        public int NGOid { get; set; }
    
        public virtual NGOTable1 NGOTable1 { get; set; }
    }
}
