//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zerohunger.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodTable
    {
        public int id { get; set; }
        public string Foodname { get; set; }
        public string foodamount { get; set; }
        public int Collectrequestid { get; set; }
    
        public virtual RequestTable RequestTable { get; set; }
    }
}
