//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zerohunger.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZeroHungerEntities : DbContext
    {
        public ZeroHungerEntities()
            : base("name=ZeroHungerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeTable1> EmployeeTable1 { get; set; }
        public virtual DbSet<FoodTable> FoodTables { get; set; }
        public virtual DbSet<NGOTable1> NGOTable1 { get; set; }
        public virtual DbSet<RequestTable> RequestTables { get; set; }
        public virtual DbSet<RestuarentTable> RestuarentTables { get; set; }
        public virtual DbSet<LoginTable> LoginTables { get; set; }
    }
}
