//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zerohunger.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGOTable1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGOTable1()
        {
            this.EmployeeTable1 = new HashSet<EmployeeTable1>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public int completedrequest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeTable1> EmployeeTable1 { get; set; }
    }
}
