//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zerohunger.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestTable()
        {
            this.FoodTables = new HashSet<FoodTable>();
        }
    
        public int id { get; set; }
        public int Restuarentid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodTable> FoodTables { get; set; }
        public virtual RestuarentTable RestuarentTable { get; set; }
    }
}
